### ISSUE TITLE
Feedback for HW2 task1

### ISSUE THREAD

**Issue by MaksHostroushko** [serdytyi/RubyHW#1]
https://github.com/serdytyi/RubyHW/blob/4ce168bdbc6d00fbceb93378190283696282d00e/HW2/task1.rb
First of all, you did great work!
But let's refactor it

8. `p arr.delete_if { |a| a.odd? }`
We can use `&:` operator. In this case, your solution will be a little bit shorter
`arr.delete_if(&:odd?)`

10. `p arr.select { |el| el%3==0 }`
Please, remember about spaces in your code
`arr.select { |el| el % 3 == 0 }`

13. `p arr.map { |el| el > 0 && el<=255  ? el.chr : el  }`
First of all, remember about spaces in your code
Also, try to use method `positive?` instead of `>0`
` arr.map { |el| el.positive? && el<=255 ? el.chr : el }`

**Comment by serdytyi** [comment]
Fixed,thanks.
